### ISSUE TITLE
Vague error message on confirmation failure

### ISSUE THREAD

**Issue by clausmith** [onecodex/onecodex#100]
When `fastx-proxy` fails to confirm the upload, the CLI only outputs the following:

```

ERROR: Upload failed. Please contact help@onecodex.com for assistance.
Please feel free to contact us for help at help@onecodex.com

```

We should say something like:

```

ERROR: Upload failed - <message from fastx-proxy>.
Please feel free to contact us for help at help@onecodex.com

```

**Comment by clausmith** [comment]
Backlogging this, the issue isn't what I thought it was.

**Comment by polyatail** [comment]
It seems like 400-level errors are already verbosely reported. Do we want to spit something out for 500-level errors? Under what circumstances can we expect fastx-proxy to return those and do we want users to see them?
