### ISSUE TITLE
Scope changes in upload threading

### ISSUE THREAD

**Issue by bovee** [onecodex/onecodex#109]
This code is a little confusing and hard to debug (there was some confusion on issue #106). If this isn't giving us a significant perf boost, it's possible we want to remove it.

- [ ] Decide whether to remove upload threading from CLI

**Comment by polyatail** [comment]
Previously, we were uncompressing, validating/interleaving, and recompressing files locally. This meant  it was more likely to be CPU-bound during the upload process. Now that we are blindly interleaving (or in the case of single-ended files, sending them as-is), we're more likely to be IO-bound or to hit the upstream bandwidth cap of the user. The code for threading isn't that substantial, but it may not be necessary. I could go either way.
