### ISSUE TITLE
Add/enhance compatibility with simplejson and remove warning

### ISSUE THREAD

**Issue by boydgreenfield** [onecodex/onecodex#111]
This is upstream in Potion-Client and could be fixed either there or via a monkey patch. See https://github.com/onecodex/onecodex/issues/66 for more details. It'd be nice to finally remove this warning as many users do just `pip install onecodex` globally and thus run into this issue.

**Comment by bovee** [comment]
See original issue: https://github.com/onecodex/onecodex/issues/66
