### ISSUE TITLE
Add `--include-children` option to filter reads script

### ISSUE THREAD

**Issue by boydgreenfield** [onecodex/onecodex#114]
This would be very useful for, e.g., fetching all reads for a given species _and all of its strains_.

**Comment by boydgreenfield** [comment]
Note we should also add a `--include-parents` flag to get things _at or above_ a given tax ID too.

@clausmith preference on `--with-children`/`--with-parents` vs. `--include-children`/`--include-parents`? Former is shorter so perhaps better.

**Comment by polyatail** [comment]
Question: for --with-parent, is the desired behavior to produce only the direct ascendants (if that's a thing) of the specified tax_id? For E. coli, for example, Bacteria, Proteobacteria, Gammaproteobacteria, Enterobacteriales, Enterobacteriaceae, Escherichia, E. coli and no others.

**Comment by boydgreenfield** [comment]
@polyatail Yes I think so. The idea here is that those are all of the reads that could presumably map back to a given genome via alignment or some orthogonal method.
