### ISSUE TITLE
Add better error message when trying to upload anonymously

### ISSUE THREAD

**Issue by boydgreenfield** [onecodex/onecodex#117]
This is not a good error message. We should catch and prompt for login directly. May be worth having a `login_required` or similar decorator that we can put on individual click functions to do this check and prompt as needed.

```
10:34:12 (ocx) {master} ~/OC/create-react-app-antd$ onecodex upload ~/Downloads/MSA-1000.16S.short.fastq 
No One Codex API credentials found - running anonymously
Uploading: Preparing upload(s)...    
ERROR: 'HTTPError' object does not support indexing
Please feel free to contact us for help at help@onecodex.com
```

**Comment by polyatail** [comment]
I addressed this by adding a login_required decorator in cli.py and requiring logins for all functions but login/logout.

**Comment by boydgreenfield** [comment]
@polyatail Let's discuss, we don't _technically_ require that a user is logged in to use the API, e.g., they can access public samples by ID, but in practice that's probably not that useful via the CLI.

**Comment by polyatail** [comment]
Hmm ok... I added back in the anonymous login for non-upload functions. But stuff like 'analyses' and 'samples' comes back empty.

**Comment by boydgreenfield** [comment]
@polyatail As discussed, I like your requirement on everything but `login` and `logout`.
