### ISSUE TITLE
Snake case metadata names by default when uploading

### ISSUE THREAD

**Issue by boydgreenfield** [onecodex/onecodex#118]
In our frontend uploader, we snake case metadata field names. Via the CLI or `ocx.Samples.upload` method, however, we do not. This leads to inconsistent naming, e.g.,:

![image](https://user-images.githubusercontent.com/535969/47890701-4c3ff080-de0d-11e8-8d88-d7d054868286.png)

We should consider automatically snake casing these names in our library directly (and perhaps enforcing these on the API side).

**Comment by polyatail** [comment]
I think it probably does this in the CLI here:

```python
            if len(split_metadata) > 1:
                metadata_value = split_metadata[1]
                appendables['metadata'][snake_case(split_metadata[0])] = metadata_value

    appendables = validate_appendables(appendables, ctx.obj['API'])
```

Where on the API handles this?
