### ISSUE TITLE
Specify minimum pip version in README

### ISSUE THREAD

**Issue by boydgreenfield** [onecodex/onecodex#120]
When installing the `onecodex` library, old versions of pip appear to give the following error message:

```
Could not find a version that satisfies the requirement onecodex (from versions: )
```

We should:
- [ ] Investigate if this is truly a pip issue or rather how we're packaging this repo; and
- [ ] Update our README and docs.onecodex.com to address this edge case (system in question was Mac running El Cap and pip 6)

**Comment by polyatail** [comment]
@boydgreenfield Any more info available on this one? Sounds like it could be an unhandled connectivity or similar issue in an earlier pip version, idk.

**Comment by boydgreenfield** [comment]
@polyatail No more diagnostically useful info, sadly. If we can't reproduce we can close this until we can.
