### ISSUE TITLE
Make resource creation or lookup easier

### ISSUE THREAD

**Issue by polyatail** [onecodex/onecodex#130]
Allow users to create new instances of e.g., Tags with something like `Tags(name='isolate')` rather than creating a new instance, setting the name parameter, and calling save(). When adding a Resource to a ResourceList, allow strings to be passed and looked up, as in `sample.tags.append('isolate')` which will find the right tag and add it as an object.

**Comment by boydgreenfield** [comment]
I like this append idea, but .append(Tag(‘tag_name’)) seems like a better, less magic-y syntax to support.
