### ISSUE TITLE
Implement dendrograms for heatmaps

### ISSUE THREAD

**Issue by bcamarda** [onecodex/onecodex#134]
Our current `viz.plot_distance` function returns a heatmap with a dendrogram. We would like to add that functionality using `altair`.

**Comment by polyatail** [comment]
It seems more difficult to version and edit `altair` or `vega` than it is to simply draw some trees from `scipy` using lines. Maybe we can come back to that if/when those guys add support for trees and use our manually-drawn trees until then.
