### ISSUE TITLE
Explore static image rendering options for notebooks

### ISSUE THREAD

**Issue by polyatail** [onecodex/onecodex#145]
How are our existing notebooks affected by switching to altair from matplotlib?

**Comment by polyatail** [comment]
Added an option to return `altair` chart objects rather than outputting them into the notebook. These chart objects can be used to save an svg or png:

```python
chart = samples.plot_pca(return_chart=True)
chart.save('image.png', scale_factor=3)
```
`scale_factor` here increases the resolution of the images. In our notebook Dockerfile, I added `selenium` and `chromedriver` to get this working via headless chrome. Chrome didn't work unless `--cap-add SYS_ADMIN` was specified on the `docker run` command line. [Here](https://docs.docker.com/engine/reference/run/) they say this flag allows us to `Perform a range of system administration operations.` Whatever that means.

@boyd @clausmith Think it will be a problem to enable this in the notebook service?

**Comment by polyatail** [comment]
The new notebook image (with headless chrome) does static rendering on the notebook service. I guess that means this option is already enabled? 👍 

I think the way to do this so that images can be statically rendered and exported as a notebook in HTML or PDF is to either add a `render_static` kwarg to plotting functions or a global on `onecodex.Api` objects that turns on static rendering. When enabled, I'll have altair save high-res PNGs by default and display them in the notebook with `IPython.display.Image`

**Comment by boydgreenfield** [comment]
@polyatail Note for later: `--cap-add SYS_ADMIN` looks like it may be required locally (Docker for Mac) but is not required on Linux and should **not** be used. We're leaving this off in the notebook service.

**Comment by polyatail** [comment]
To note our discussion earlier, the preferred behavior is to have images rendered statically as PNGs when run from `nbconvert` and as interactive plots when in a jupyter notebook.

According to [this issue](https://github.com/jupyter/notebook/issues/2587) there is no way of detecting `nbconvert`, but we can presumably set and detect our own environment variable to get this to happen.

**Comment by boydgreenfield** [comment]
@polyatail We'll just have to set an environment variable then. Too bad, but reasonable. Do you know if the "Save as HTML" function in the notebook file menu calls `nbconvert` under the hood? I.e., will that generate interactive or static images? I think the former is _fine_ actually, so really just curious.

**Comment by polyatail** [comment]
Okey dokey, I created an environment variable `OCX_NBCONVERT` that is set in @clausmith's `notebook_report.py` script. Viz will enable one of three renderers: 1) high-res PNG if exporting a notebook report PDF with the environment variable set, 2) embedded/interactive if inside an ipython session, 3) altair's default renderer otherwise.

What we should do next, perhaps in another issue, is modify the dropdown export list in our notebooks to contain only the options that actually work (probably in the static notebook js). We can also add an extension that calls our notebook report script to that dropdown.
