### ISSUE TITLE
FASTQ file with -- lines silently gets truncated

### ISSUE THREAD

**Issue by boydgreenfield** [onecodex/onecodex#161]
A FASTQ file with `--` on lines will silently get truncated by the validator rather than failing as it should. Example file:

```
@HEADER
GCGGAATCGCCTTCCTTCCCGGGCAACAGTCGCATCGTT
+
JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ
--
@HEADER2
GCGGAATCGCCTTCCTTCCCGGGCAACAGTCGCATCGTT
+
JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ
``` 

Will only upload a 1 read file.

**Comment by boydgreenfield** [comment]
Note this is caught by the proxy, so we can decide whether to fix in the CLI or just handle via the proxy:

![image](https://user-images.githubusercontent.com/535969/50648821-0f899600-0f31-11e9-9d08-370b09a13d87.png)

**Comment by polyatail** [comment]
Hmm... my two cents, we should fix this in the validator and pin a release ASAP, then perhaps shoot for refactoring the uploader and switching over to the proxy 100% of the time for CLI uploads in the next 1-2 sprints.

**Comment by polyatail** [comment]
Here are some potential ways of solving this issue in the CLI:

- Switch from `match()` to `finditer()` which will find all FASTQ records in the buffer, skipping bad lines
- Count number of lines in the file. For FASTQ, this should be divisible by 4 and the result of that division should equal the number of records we parse.
- Parse file as groups of four lines, checking for a FASTQ regexp (or other) match for each.
