### ISSUE TITLE
Filter reads script is slow

### ISSUE THREAD

**Issue by boydgreenfield** [onecodex/onecodex#163]
A very filter read subsettings script like [this one](https://gist.github.com/boydgreenfield/80d53a9f67c418e3aeafb9d630cb56a5) does 5-10M reads / minute in Python. Our `filter_reads` script appears to have a _lot_ more overhead than this. We should investigate and fix if that overhead isn't coming with some very nice safety and handrails.

**Comment by polyatail** [comment]
I imagine any differences are coming from either 1) that filter_reads iterates over the TSV and FASTX files consecutively rather than concurrently, or 2) FASTXTranslator is slow.

**Comment by boydgreenfield** [comment]
@polyatail I'd guess it's the latter... though we should probably also only do one pass?

**Comment by polyatail** [comment]
`skbio.io` is very slow. I'm getting 250k reads/min =( The same code with a generator function yielding four lines at a time does 3.5M/min.

**Comment by polyatail** [comment]
Perhaps we can add an option `--validate` to use skbio iterators instead of a simple four line generator function, leaving it off by default.

**Comment by boydgreenfield** [comment]
@polyatail Yea... that's fine with me. Presumably any new data in our platform should validate anyway. We can always make validate the default in the future if we see lots of errors likely related to this. 

Let's set it up as a `--validate`/`--do-not-validate` pair of options and just default to the former at the moment (how uploads _currently_ work).
