### ISSUE TITLE
User reports inability to install package from pip on 2.7.10

### ISSUE THREAD

**Issue by polyatail** [onecodex/onecodex#175]
User has OS X El Capitan 10.11.6, Python 2.7.10.

```
$ pip install onecodex
Collecting onecodex
Could not find a version that satisfies the requirement onecodex (from versions: )
No matching distribution found for onecodex
```

Was using pip `6.1.1`, but tried upgrading and it still didn't work:

```
$ pip install --upgrade pip
Requirement already up-to-date: pip in /Library/Python/2.7/site-packages
```

A post [here](https://stackoverflow.com/questions/49748063/pip-install-fails-for-every-package-could-not-find-a-version-that-satisfies) suggests that it's a problem with pip and this OS X version, which can be solved by running:

```
$ curl https://bootstrap.pypa.io/get-pip.py | python
$ pip install --upgrade setuptools
```

**Comment by bcamarda** [comment]
Reporter did not respond to inquiries, will not fix.
