### ISSUE TITLE
Leading zero is erroneously stripped from all-numeric IDs

### ISSUE THREAD

**Issue by boydgreenfield** [onecodex/onecodex#200]
For example, `ocx.Samples.get('0980548691454960')` gets rendered out as having an ID of `980548691454960`. This is _probably_ a too-clever auto-integer coercion happening in our code or upstream in `potion-client`.

Note that this only affects UUIDs that are _all_ numbers and have a leading zero (~1 in 2000). This erroneously truncated ID is saved as the object `id` property, so we will fail to re-synchronize changes to this sample.

**Comment by audy** [comment]
https://github.com/biosustain/potion-client/blob/master/potion_client/resource.py#L111-L112

**Comment by bcamarda** [comment]
Also look at what's upstream. Update to newest version.

**Comment by clausmith** [comment]
Re-opening - I just saw this happen again in a notebook running `v0.6.0` of the library (which was released long after we fixed this bug).
