### ISSUE TITLE
Report PDF export doesn't work unless report.set_date() is called

### ISSUE THREAD

**Issue by polyatail** [onecodex/onecodex#206]
The fix is to change the requirement that `report.set_date()` be called from within an IPython session, since `OneCodexHTMLExporter` can call it from nbconvert.

**Comment by boydgreenfield** [comment]
@polyatail Can we not have it fallback to use the current date? It feels more natural that `report.set_date` would just override the current date and time.

**Comment by polyatail** [comment]
For sure, that's what it does/is supposed to do. Just a bug.
