### ISSUE TITLE
Add support for customizing sample labels

### ISSUE THREAD

**Issue by clausmith** [onecodex/onecodex#221]
A user should be able to customize how the samples are labelled along an axis. For example, specifying that the plot be labelled by `external_sample_id`, or a lambda function.

**Comment by polyatail** [comment]
Technically, this still exists by calling, for example:

```python
# method 1
samples._collate_metadata(label="metadata field")

# method 2
samples._collate_metadata(label=lambda metadata: "my formatter {}".format(metadata.field))
samples.plot_pca()
```

But I agree that it should be made more accessible. Perhaps making collate_metadata public?

**Comment by boydgreenfield** [comment]
@polyatail I’d error towards making this doable in the `plot_*` calls directly. Seems like exposing metadata collation is quickly getting into “expert end user” territory and I think a wider audience would like/use this functionality.
