### ISSUE TITLE
Look into issues when using plot_bargraph with rank="kingdom"

### ISSUE THREAD

**Issue by clausmith** [onecodex/onecodex#222]
For example, these two plots are the exact same `SampleCollection`, plotted with `rank="phylum"` and `rank="kingdom"`

<img width="598" alt="screenshot 2019-03-01 10 49 57" src="https://user-images.githubusercontent.com/2334701/53649334-e83d0580-3c0f-11e9-9ea1-042811e1ec96.png">
<img width="575" alt="screenshot 2019-03-01 10 50 10" src="https://user-images.githubusercontent.com/2334701/53649335-e83d0580-3c0f-11e9-9c01-9989190f0d0f.png">

**Comment by polyatail** [comment]
This might be an issue with ranks in our taxonomy, for example:

```python
samples.plot_bargraph(rank='superkingdom')
```

<img src="https://user-images.githubusercontent.com/784132/53661023-394ef880-3c14-11e9-8944-b0a4a90207e4.png" width=600>

**Comment by boydgreenfield** [comment]
Yep! ... maybe we should warn if you select a rank that’s actually only displaying a (very small) fraction of the data? That’s definitely low priority, but it does appear Chris got bit by this one 😉

**Comment by polyatail** [comment]
Options:

1) Merge superkingdom and kingdom
2) Change docstring to refer to superkingdom
3) Throw warning if superkingdom used
