### ISSUE TITLE
Improve API for filtering contents of SampleCollection

### ISSUE THREAD

**Issue by polyatail** [onecodex/onecodex#226]
A user might filter the contents of a SampleCollection and want the results to be a SampleCollection rather than a native list. Consider the following:

```python
samples = [s for s in ocx.Samples.all() if s.filename.endswidth('_trimmed_fastq.gz')]
```

`ocx.Samples.all()` will return a SampleCollection, but the above list comprehension will return a native list. There should be a way for a user to put that list into a new SampleCollection. Presently, the way to do that is:

```python
# method 1
from onecodex.models.collection import SampleCollection
from onecodex.models import Samples

sample_res = [s._resource for s in samples]
sample_coll = SampleCollection(sample_res, Samples)

# method 2
samples = ocx.Samples.all()

for s in samples:
    if not s.filename.endswidth('_trimmed_fastq.gz'):
        samples.remove(s)
```

This is obviously pretty janky. Here are some alternatives:

- Allow instantiation of SampleCollection from a list of Samples
- A `.filter()` method on SampleCollection
- Better filtering on `Samples.where()`

**Comment by boydgreenfield** [comment]
Well, certainly `method 2` is cleaner and doesn't expose a bunch of internals, so let's do that for the moment. 

In terms of paths forward, maybe we should do all 3 of your alternatives @polyatail?

Here's what I'm thinking specifically:

1. This would just be nice. Out of curiosity, why does `SampleCollection` need `Samples` as its second argument though? That's not super obvious. A constructor that assumes `Samples` for the model and allows passing our model vs. the Potion-Client `_resource` would be nice for general use.

2. I'd err towards a `.filter(lambda x: x.filename.startswith("FA1-"))` style method.  

3. I'm wary of having random `kwargs` sometimes filter on the server-side and sometimes filter in memory... that seems like it'll lead to unpredictable performance and bad client code. _But_ maybe it'd be useful to support a `filter=` kwarg that just calls #2 right after? This then hides some of those details and leads to pretty ergonomic code:

```
# Prior idiomatic code
samples = ocx.Samples.all()
samples = [x for x in samples if x.filename.endswith("_trimmed.fastq.gz")]

# New code. Better?
samples = ocx.Samples.where(filter=lambda x: x.filename.endswith("_trimmed.fastq.gz"))
```
