### ISSUE TITLE
Read-level results in client API

### ISSUE THREAD

**Issue by boydgreenfield** [onecodex/onecodex#230]
Currently, we say we do not support downloading read-level results in the [client API documentation](https://docs.onecodex.com/v1/reference#classification-results-read-level), but we actually do have a `.readlevel` method on the classification object. This just returns a pre-signed link available for download.

We should consider a method like `.download_read_level_results` (but pithier) for downloading this and _possibly_ doing some of the filtering and manipulation in a notebook environment.

**Comment by bcamarda** [comment]
Let's make this a private method `_readlevel`
