### ISSUE TITLE
exit on KeyboardInterrupt when user does ctrl-C during sample.download()

### ISSUE THREAD

**Issue by audy** [onecodex/onecodex#238]
`KeyboardInterrupt` gets caught so that the partially-downloaded file can be removed but then the exception is never re-raised. This means that you can't do ctrl-C if you change your mind about downloading a bunch of samples: https://github.com/onecodex/onecodex/blob/master/onecodex/models/helpers.py#L136-L138

**Comment by boydgreenfield** [comment]
Closed in #239.
