### ISSUE TITLE
Fix handling of "null\n" returned by fastx-proxy

### ISSUE THREAD

**Issue by polyatail** [onecodex/onecodex#247]
In `process_api_error` it's possible for fastx-proxy to return "null\n" which is apparently valid JSON that does not throw a ValueError. We should catch that case and turn set `error_json = {}`

https://sentry.onecodex.com/onecodex/one-codex-cli/issues/3976/

**Comment by boydgreenfield** [comment]
The proxy shouldn't return this value, but agreed we should handle it in case it does... Gross. 😦

**Comment by boydgreenfield** [comment]
I've fixed this upstream in the proxy.
