### ISSUE TITLE
Move logger configuration into CLI initialization vs. in cli.py

### ISSUE THREAD

**Issue by boydgreenfield** [onecodex/onecodex#254]
Otherwise, any imports of `cli.py` can trigger logging initialization, which may not be desirable for library end-users.

**Comment by polyatail** [comment]
We already have the `onecodex` namespace logger in `onecodex/__init__.py`. Should we just use that for CLI messages instead of modifying the root logger in `onecodex/cli.py`?

**Comment by boydgreenfield** [comment]
@polyatail Probably... let's discuss tomorrow and we can do a few merges for a `0.6.0` CLI bump. :)
