### ISSUE TITLE
Support direct-to-S3 uploads for very large files, deferring validation

### ISSUE THREAD

**Issue by boydgreenfield** [onecodex/onecodex#264]

**Comment by Keats** [comment]
How do we define very large files? >50GB?

**Comment by boydgreenfield** [comment]
@Keats Yes probably in that range. But depending on how we get the new "validate later" setup working, we may want to do something like:
* (1) For small files, always upload and do synchronous validation
* (2) For big-_ish_ files, upload with synchronous validation but potentially skip re-compression and do that in a separate step (i.e., repurpose async validation to handle the compression)
* (3) For very large files, consider disabling synchronous validation entirely. Validation will then happen asynchronously as an "import".

I'm not sure if the 2nd category simply overcomplicates things. In either case, we should always do (3) as a fallback in the case that synchronous validation fails with a non-400 code.

**Comment by Keats** [comment]
I think we can skip 2 as it is just not really worth the hassle imo

**Comment by boydgreenfield** [comment]
@Keats That's fine with me.
