### ISSUE TITLE
Normalized plots still list "readcount_w_children"

### ISSUE THREAD

**Issue by clausmith** [onecodex/onecodex#274]
When you make a plot and pass `normalize=True` (or if the data gets auto-normalized), the tooltip still lists the metric as being `readcount_w_children`. For normalized data _not_ based on abundances, this should say "Proportionalized Readcount" or "Normalized Readcount", otherwise it should say "Relative Abundance".

<img width="520" alt="Screenshot 2019-07-16 13 15 25" src="https://user-images.githubusercontent.com/2334701/61315093-0759bf80-a7cc-11e9-82bd-582b796aa5e8.png">

**Comment by polyatail** [comment]
The thing is, we have two different ideas of relative abundance. The `abundance` we calculate using metagenomic data, and dividing `readcount_w_children` by `sum(readcount_w_children)`. Should we distinguish between those two?

**Comment by clausmith** [comment]
Yes for sure. I think @boydgreenfield had some preferred language here but we do need to distinguish whether we're looking at absolute readcounts, normalized readcounts, or the estimated abundances.

**Comment by boydgreenfield** [comment]
Let's discuss during planning next week.

**Comment by boydgreenfield** [comment]
We should add information to the README on how to generate collections that use abundances vs. readcounts (and what `None`/`auto` will do), when we're using which and make sure that the various `kwargs` are clear. 

See also #275.
