### ISSUE TITLE
Normalizing should default to abundances if available

### ISSUE THREAD

**Issue by clausmith** [onecodex/onecodex#275]
Right now it looks like passing `normalize=True` always _proportionalizes_ the data, instead of pulling the abundances when available.

**Comment by boydgreenfield** [comment]
@clausmith I think we should consider a more explicit API here, e.g., `abundances=True/False`. I'm a little worried about allowing users to inadvertently mix metrics.

**Comment by polyatail** [comment]
I think the only way right now to switch to abundances is something like this:

```python
from onecodex.models import SampleCollection

samples_with_abundances = SampleCollection(samples, field="abundance")
```

API could definitely be improved for that.

**Comment by bcamarda** [comment]
close in favor of #274
