### ISSUE TITLE
Unicode characters in notebooks not rendering properly to PDF

### ISSUE THREAD

**Issue by clausmith** [onecodex/onecodex#289]
For example, if we have a string such as "Naïve" in the notebook, it gets rendered out as:
 
<img width="53" alt="Screen Shot 2019-07-24 at 12 42 38 PM" src="https://user-images.githubusercontent.com/2334701/61811927-896f6700-ae10-11e9-836c-a0329e1c052b.png">

**Comment by polyatail** [comment]
It's probably because the notebook PDFs use `Palladio Uralic`, this free Russian Palatino font. I found that it was the closest to actual Palatino on Linux. If we're cool switching to e.g., `FreeSerif` then this problem will go away.

**Comment by polyatail** [comment]
Okay, I did some hunting for alternative fonts and came up with this.

**Palladio Uralic (current)**
![image](https://user-images.githubusercontent.com/784132/61898639-a4081580-aece-11e9-9fb5-0d667980ce25.png)

**TeX Gyre Pagella**
![image](https://user-images.githubusercontent.com/784132/61898538-673c1e80-aece-11e9-90ec-3d7be4c32bc3.png)

I'm going to switch over to Pagella in the next release.
