### ISSUE TITLE
Warn and ask user to confirm on uploading many files

### ISSUE THREAD

**Issue by boydgreenfield** [onecodex/onecodex#29]
We've had a few cases where users have accidentally uploaded more files than intended because of support for glob `my_fasta*` syntax.

For some reasonable threshold `n`, we should consider:
- Warning and prompting for user confirmation if they try to upload `> n` files
- We should also probably had a `--force` or similar flag that _doesn't_ trigger this, in the case where a user wants to upload programmatically / without user input

**Comment by polyatail** [comment]
Opting not to implement this.
