### ISSUE TITLE
Not every ClassificationRun has a Passed Filter column

### ISSUE THREAD

**Issue by polyatail** [onecodex/onecodex#290]
The `subset_reads` script breaks when a user specifies a `ClassificationRun` like `RefSeq Complete Genomes` that doesn't have a `Passed Filter` column. If possible, we should figure out if the script is going to fail _before_ launching rather than having it throw an exception.

https://sentry.onecodex.com/onecodex/one-codex-cli/issues/4638/

**Comment by boydgreenfield** [comment]
If that column doesn't exist (which it doesn't for legacy classifications as well as those which fail filtering), we should just assume `Passed Filter` is `True` and do a `.get()`.
