### ISSUE TITLE
Plotting functions on ocx accessor don't work after renaming the index

### ISSUE THREAD

**Issue by clausmith** [onecodex/onecodex#303]
The following code causes a `KeyError` along the lines of `None of ... are in the [index]`:

```
all_df = samples.to_df()
all_df = all_df.rename(index=samples.metadata["external_sample_id"])
all_df.loc[df.index].ocx.plot_bargraph()
```

If you drop the `ocx.plot_bargraph()` and just have the following:

```
all_df = samples.to_df()
all_df = all_df.rename(index=samples.metadata["external_sample_id"])
all_df.loc[df.index]
```

Then everything is hunky-dory.

**Comment by polyatail** [comment]
Looking closer I realize that pretty much all of the viz methods rely on dataframes being indexed by `classification_id`. I'm not sure how we can get around this, since any kind of (potentially) weird manipulation to the data frame could result in the wrong stuff being plotted. Ideas?

**Comment by boydgreenfield** [comment]
@clausmith Why do you need to rename the index by another ID vs. using a different labeling function? This may be hard to reliably support.

**Comment by clausmith** [comment]
I was trying to filter the dataframe by `external_sample_id` I think. In restrospect I could have made a filtered `SampleCollection`.

**Comment by clausmith** [comment]
I think one possible solution is to have `plot_bargraph` be a generic helper that plots a stacked bar plot of `index vs columns` in the dataframe.

**Comment by polyatail** [comment]
If changing the index is only to filter, I think this is probably a wontfix... especially since you can use something like `samples.filter(lambda s: s.metadata.external_sample_id.startswith("foo"))`

**Comment by boydgreenfield** [comment]
@clausmith Closing this one. Let's try to use `.filter` as our idiomatic solution for now. We can re-evaluate if we keep running into this case.
