### ISSUE TITLE
Axis labels don't work with plot_distance

### ISSUE THREAD

**Issue by clausmith** [onecodex/onecodex#304]
Passing `xlabel` or `ylabel` to `plot_distance` doesn't appear to have any effect on the resulting plot.

**Comment by bcamarda** [comment]
Let's remove this from the docstring

**Comment by clausmith** [comment]
There's no bug here - I wasn't paying close enough attention to what the docstring says. For reference, `xlabel` and `ylabel` control the axis *titles*, while the `label` kwargs controls what metadata field.

Since this is a heatmap and both axes are the same, I'm just going to derive the axis titles from `label` and remove the `xlabel` and `ylabel` kwargs.

**Comment by polyatail** [comment]
But now the axis labels can not be overridden? This seems like a loss of functionality IMO.
