### ISSUE TITLE
Use abundances by default

### ISSUE THREAD

**Issue by polyatail** [onecodex/onecodex#310]
When a new `SampleCollection` is instantiated, try to use abundance data if it is available for all samples. If it is not, issue a warning and fallback to readcount_w_children.

**Comment by polyatail** [comment]
This is blocked on getting the API to return the cumulative abundances at all taxonomic ranks (presently, it's only calculated for species). That, in turn, is blocked on rainbow sketching.

**Comment by bcamarda** [comment]
Blocked on Rainbow Sketching
