### ISSUE TITLE
Auto-complete not working for uploads

### ISSUE THREAD

**Issue by boydgreenfield** [onecodex/onecodex#320]
I think this is a regression, but may be specific to my machine. cc @polyatail can you repro on the latest version (`v0.7.1`)?

**Comment by polyatail** [comment]
Seems to still work for me. I cleaned out my `.bash_profile` and deleted `/usr/local/etc/bash_completion.d/onecodex` and reinstalled `onecodex`, still worked.

Do you have `bash_completion.d` installed? Is `[ -f /usr/local/etc/bash_completion ] && . /usr/local/etc/bash_completion` in your `.bash_profile` ?

**Comment by boydgreenfield** [comment]
@polyatail Weird. So I can autocomplete _commands_, i.e., `onecodex samp` will tab-complete to `onecodex samples` but I can't autocomplete filepaths, i.e., `onecodex upload /Users/` will not let me tab out and see various options (nor will `~/Downloads/`).

Same for you or is that working?

**Comment by polyatail** [comment]
Still seems to be working for me

```
(onecodex367) mewtwo:onecodex as$ onecodex --version
onecodex, version 0.7.2
(onecodex367) mewtwo:onecodex as$ onecodex upload setup.
setup.cfg  setup.py
```

**Comment by boydgreenfield** [comment]
OK, well then something must be borked for me. I'll close this.
