### ISSUE TITLE
Allow Bray-Curtis with normalized readcounts (vs. non-normalized data)

### ISSUE THREAD

**Issue by boydgreenfield** [onecodex/onecodex#322]
This is perfectly valid and more correct when used naively (as non-normalized readcounts in part display deltas due to read depth variability). We can either call out to `sklearn` (which doesn't have this restriction) or just do some coercion into pseudo-normalized integer values (i.e., multiply our normalized values by a large constant) and use `skbio`.

**Comment by bcamarda** [comment]
We might just need to pin a new notebook service here?

**Comment by bcamarda** [comment]
Duplicate of #291
