### ISSUE TITLE
Update altair to v4

### ISSUE THREAD

**Issue by boydgreenfield** [onecodex/onecodex#336]
**Known bugs/issues to address and test for**:
- [x] Need to update use of deprecated `rangeStep` property in box and whiskers plots
- [ ] Resolve warning about scale bindings for non-continuous domains:

![image](https://user-images.githubusercontent.com/535969/77508947-1b5cc300-6e29-11ea-8519-a1c9a6c72355.png)

- [ ] Resolve event source `window` warning:

![image](https://user-images.githubusercontent.com/535969/77508894-fb2d0400-6e28-11ea-9f5c-a7351771de20.png)

- [ ] Generally make sure entire demo notebook (blog post) renders as well or more nicely than before :) 
- [ ] Check basic tutorial notebook
- [ ] Check advanced tutorial notebook

**New features to evaluate** (see [this link](https://github.com/vega/vega-lite/releases/tag/v4.0.0)):
- [ ] Interactive legends
- [ ] Look at responsive charts (cc @Keats)

_Note: The above can be scoped as separate issues and implemented as enhancements after a `v0.8.0` release too_

**Comment by Keats** [comment]
For rangeStep: https://github.com/onecodex/onecodex/pull/331/files#diff-8a33e69199107e3934479073d5aecd90
