### ISSUE TITLE
Add support for calculating Unifrac distance matrices

### ISSUE THREAD

**Issue by clausmith** [onecodex/onecodex#345]
In our `beta_diversity()` functions, we only support `braycurtis`, `jaccard`, and `cityblock` as values for the `metric` arg. 

We already support calculating Unifrac (weighted and unweighted) distances in `plot_distance`, so we should add support for outputting these as distance matrices as well.

**Comment by lynchde** [comment]
We might also consider adding support for Aitchison distance. We currently support it for ATCC control analysis (although we are revisiting what that looks like https://github.com/onecodex/control-analysis/issues/20).

**Comment by clausmith** [comment]
Turns out we actually do already support this, it's just in a separate function (`SampleCollection.unifrac()` vs `SampleCollection.beta_diversity()`). We should probably add an `weighted_unifrac` and `unweighted_unifrac` as metrics to the latter that alias to `.unifrac()`.

**Comment by clausmith** [comment]
Added noted about supporting Aitchison distance in #349.
