### ISSUE TITLE
Mutating array relationships directly does not work

### ISSUE THREAD

**Issue by boydgreenfield** [onecodex/onecodex#40]
Currently, `sample.tags.append(new_tag)` counterintuitively fails, and does not include `new_tag`. This is because we're creating the `tags` attribute on the fly and wrapping the underlying `potion-client` resource, i.e., creating a new list with each `__getattr__` call. 

The TODO here is to update how we handle arrays in the API so that the above operations (as well as `pop`, etc.) work properly.

In the meantime, users should use the following workaround:

```
tag_list = sample.tags
tag_list.append(new_tag)
sample.tags = tag_list
tag_list.save()
```

**Comment by polyatail** [comment]
I think there's a not-too-difficult path to fixing this, by creating a new ResourceList object that emulates a list. Well, it mostly just **is** a list, but it passes actions down the line to the underlying _resource object that, in the example given by @boydgreenfield, doesn't get updated.
