### ISSUE TITLE
Improve control-C support during uploads

### ISSUE THREAD

**Issue by boydgreenfield** [onecodex/onecodex#42]
For samples over 5GB, this causes the CLI progress bar to take off before the `Aborted!` eventually gets printed. We should more gracefully handle control-C here and in the normal <5GB upload case.

**Comment by polyatail** [comment]
The solution to this issue is more substantial than it seems. We should add a route to the API to cancel uploads in progress, so we don't leave partially uploaded files hanging. On Ctrl+C, this route should be requested before closing.
