### ISSUE TITLE
`onecodex login` throwing errors on macOS and ubuntu 20.04 for python version 3.9

### ISSUE THREAD

**Issue by jwin4740** [onecodex/onecodex#421]
File "/Users/jameswinkle/py3.9.7_venv/lib/python3.9/site-packages/click/core.py", line 2947, in __init__
    super().__init__(param_decls, required=required, **attrs)
TypeError: __init__() got an unexpected keyword argument 'autocompletion'

**Comment by Keats** [comment]
This will be fixed once https://github.com/onecodex/onecodex/pull/420 is merged and released. We didn't set an upper bound for a dependency and a recent version of it had breaking changes.

**Comment by jwin4740** [comment]
ok, thanks

**Comment by jwin4740** [comment]
I may like to contribute to this project. Is there anyone who can help me get this setup?

**Comment by jairideout** [comment]
@jwin4740 thanks for your interest in contributing! The [Development section](https://github.com/onecodex/onecodex/blob/master/README.md#development) of the README has info about setting up a dev environment.

I'm closing this issue now that #420 is merged and `v0.10.0` is released. Please reopen if you're still seeing errors. Thanks!
