### ISSUE TITLE
Add caching for analysis results

### ISSUE THREAD

**Issue by sminot** [onecodex/onecodex#44]
Support local caching for analysis results, specifically the data returned by `Classifications.results()`

**Comment by boydgreenfield** [comment]
These actually should be cached here: https://github.com/onecodex/onecodex/blob/master/onecodex/models/analysis.py#L30-L36.

If not, let me know and we'll get this fixed. We should also longer term evaluate options for adding a bit more user notification in a notebook environment (e.g., a progress bar or similar if fetching lots of data).

**Comment by boydgreenfield** [comment]
This is already implemented. Closing, though in the future we may want to signal this more directly to the user.
