### ISSUE TITLE
X-Total-Count does not reflect filtered values for /api/v1/samples

### ISSUE THREAD

**Issue by jdimmerman** [onecodex/onecodex#457]
Hi -

There is a bug impacting our pagination - when we filter a path, eg

```
api/v1/samples?page=1&per_page=100&expand=metadata&where={"tags": {"$containsany":[{"$ref":"some-ref"}]}}
```

the value of the header `X-Total-Count` is still reflecting the unfiltered value.

Thanks!

**Comment by jairideout** [comment]
Thanks for reporting this bug @jdimmerman! It should be fixed now.

**Comment by jdimmerman** [comment]
Thanks @jairideout!
