### ISSUE TITLE
Missing values can fail in plot routines for pandas > 0.19.2

### ISSUE THREAD

**Issue by boydgreenfield** [onecodex/onecodex#67]
In several places, we call `metadata.fillna` which blows up on pandas versions > 0.19.2. We need to update the code for Pandas 0.20. We should also consider pinning to a pandas minor version.

**Comment by clausmith** [comment]
Also need to update notebook service once we've updated the lib.

**Comment by boydgreenfield** [comment]
@clausmith Note @cindyzwang has fixed this in her PR.
