### ISSUE TITLE
`filter_reads` command should be aware of filtered reads

### ISSUE THREAD

**Issue by boydgreenfield** [onecodex/onecodex#79]
Currently, the `filter_reads` script doesn't pay attention to if reads are filtered or not. This is probably generally fine, as most reads filtered out are for specific organisms end-users won't select, but we should _probably_ default to only using filtered reads if filtering information is available and then make a `--include-filtered-reads` or `--include-removed-reads` flag for including both.

**Comment by polyatail** [comment]
Is this the same as --exclude-reads in #83 ?

**Comment by boydgreenfield** [comment]
@polyatail No, this is more subtle – and terrible written (I had to read my comment 2x to understand). We have a filtered tax ID column in our TSVs, and we "filter" out likely erroneous results and report them as 0. We should consider defaulting to that column when available.

**Comment by bcamarda** [comment]
Maybe we should rename this command `subset_reads` to make things simpler...
